name: Create release

on:
  workflow_dispatch:
    inputs:
      minecraft-version:
        required: true
        type: string
      svmm-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      name: Checking out release/${{minecraft-version}}
      with:
        ref: release/${{minecraft-version}}

    - uses: mingjun97/file-regex-replace@v1
      name: Update version number
      with:
        regex: ^version = (.*)$
        flags: gm
        replacement: "$1'${{minecraft-version}}-${{svmm-version}}'"
        include: build.gradle
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: Commit new version to branch release/${{minecraft-version}}
      run: |
        git config --global user.name '${{vars.BUILD_ACTOR_NAME}}'
        git config --global user.email '${{vars.BUILD_ACTOR_EMAIL}}'
        git commit -am "Bump version to ${{minecraft-version}}-${{svmm-version}}"
        git push
  
    - name: Create release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: 'build/libs/*.jar'
        automatic_release_tag: ${{minecraft-version}}/${{svmm-version}}
        title: ${{minecraft-version}}.${{svmm-version}}
        
